### PR TITLE
Upgrade gradlew to 2.12

### PR DESCRIPTION
**Pull request by michael-yx-wu**

### CODE REVIEW

**Comment by michael-yx-wu** [comment]
Does `gradlew.bat` appear to have gotten "replaced" because of line endings?

**Comment by uschi2000** [comment]
something's wrong with the travis build, otherwise I'm happy to accept this.

**Comment by michael-yx-wu** [comment]
Seems like it's because of conflicting groovy versions hmmm

**Comment by michael-yx-wu** [comment]
The latest release of nebula-test has compatible groovy versions so I'm upgrading to that as well

**Comment by michael-yx-wu** [comment]
Closing in favor of #17

**Pull request closed without merging**
